version: '2'
services:
    openempi-app:
        image: uwitech/ohie-cr
        ports:
            - 8080:8080
            - 3600:3600
            - 3700:3700
        depends_on:
            - openempi-db
        env_file: .env
    openempi-db:
        extends:
            file: postgresql.yml
            service: postgresql
