version: '2'
services:
    postgresql:
        image: uwitech/postgresql
        # Uncomment to persist PostgreSQL data between docker runs.
        # volumes:
        #     - ~/volumes/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=openempi
            - POSTGRES_DB=openempi
            - POSTGRES_PASSWORD=openempi
        ports:
            - 5433:5432
